packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  protobufjs: true
  unrs-resolver: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver

patchedDependencies:
  '@callstack/react-native-brownfield@3.6.1': patches/@callstack__react-native-brownfield@3.6.1.patch
