package expo.modules.hostenvironment

/**
 * Process-wide holder for the backend environment the native HOST app is
 * pointed at ("development" or "production"). The brownfield entry point
 * (ReactNativeHostManager.initialize(application, environment), generated by
 * plugins/withBrownfieldUpdates.js) publishes the host's selection here BEFORE
 * React Native boots, so the JS layer can resolve the matching gateway URL
 * instead of trusting a value baked into the bundle or cached in an OTA
 * manifest.
 *
 * Exposed to Java/Kotlin as `HostEnvironment.INSTANCE`.
 */
object HostEnvironment {
  @Volatile
  private var environment: String? = null

  /**
   * Publishes the host-selected environment. Expected values are
   * "development" or "production" (the JS wrapper treats anything else as
   * unset and falls back toward production).
   */
  fun configure(environment: String) {
    this.environment = environment
  }

  val current: String?
    get() = environment
}
